PROJECT=ifcmgkernel
PROJECT_NAME=ifcmgkernel
PROJECT_MAINTAINER=jeffk
PROJECT_COPYRIGHT=2008
PROJECT_EMAIL=jeffk@internetfilter.com
PROJECT_LICENSE=closed
PROJECT_LICENSE_FILE=$(PROJECT_TOP_DIR)/LICENSE.txt
PROJECT_README_FILE=$(PROJECT_TOP_DIR)/README.txt
PROJECT_COMPANY=Turner and Sons Productions, Inc.
PROJECT_WEBSITE=www.internetfilter.com
PROJECT_DESCRIPTION=ifcmgkernel
PROJECT_VERSION=3.0
PROJECT_IDENTIFIER=com.contextualmediagroup.ifcmgkernel
TOP_LIB_DIRS+=.
SUBLIBS=
INCLUDES+=
DEFINES+=_REENTRANT JDKSBOOST_ENABLE_POSIX JDKSBOOST_ENABLE_PTHREADS
COMPILE_FLAGS+=-Wall -pthread
LINK_FLAGS+=
PKGCONFIG_PACKAGES+=
CONFIG_TOOLS+=


BOOST_CONFIG?=$(PREFIX)/bin/jdksboost-config
JDKS2K9_CONFIG?=$(PREFIX)/bin/jdks2k9-config

LDLIBS_POSIX+=-pthread
LDLIBS_POSIX+=-lssl -lcrypto

#CONFIG_TOOLS+=$(BOOST_CONFIG) $(JDKS2K9_CONFIG)

ifeq ($(PROJECT_VARIANT),debian)
TARGET_DIR_STYLE=debian
#PACKAGE_CHOWN?=root:root
PACKAGE_CHMOD?=go-rw,u+rwX
endif

ifeq ($(PROJECT_VARIANT),ubuntu)
TARGET_DIR_STYLE=ubuntu
#PACKAGE_CHOWN?=root:root
PACKAGE_CHMOD?=go-rw,u+rwX
endif

ifeq ($(PROJECT_VARIANT),macosx)
TARGET_DIR_STYLE=macosx-library
PACKAGE_CHOWN=
PACKAGE_CHMOD=
PREFIX=/Library/contextualmediagroup/$(PROJECT)-$(VERSION)
endif




